services:
  bmkg-alert-backend:
    container_name: bmkg-alert-backend
    image: ghcr.io/dhanyyudi/bmkg-alert-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/backend:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  bmkg-alert-frontend:
    container_name: bmkg-alert-frontend
    image: ghcr.io/dhanyyudi/bmkg-alert-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://bmkg-alert-backend:8000
    depends_on:
      - bmkg-alert-backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
